### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by theodorosploumis** [theodorosploumis/awesome-drupal#1]
- [ ] Create a table of contents
 - [ ] Create a logo
 - [ ] Create a default issue template (for new additions/contributions)
 - [ ] Add list to https://github.com/sindresorhus/awesome
 - [ ] Publish to D.O.

**Comment by theodorosploumis** [comment]
Awesome list tasks

- [x] Conform with awesome-list
- [ ] Ask the maintainers at https://github.com/nirgn975/awesome-drupal to "Archive" the project and then comment to https://github.com/sindresorhus/awesome/issues/628
- [ ] Review at least 2 PRs from https://github.com/sindresorhus/awesome/pulls?q=is%3Apr+is%3Aopen
- [ ] Ask D.O. community members to add/edit links on this repository
